#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the deliverybot usb connection."
echo ""

sudo cp `sudo cp `ros2 pkg prefix deliverybot_bringup`/share/deliverybot_bringup/script/99-deliverybot-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
